# Generated by Django 4.1.4 on 2023-01-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='proimage',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
